### PR TITLE
Add `RTSharkBuilderReady::keylog_file` API

### PR DESCRIPTION
**Pull request by vvv**
Allow specifying the key log file that enables decryption of TLS traffic.

### CODE REVIEW

**Comment by BlurMedia** [comment]
Any update on this? Seems like a crucial piece of the api!

**Comment by CrabeDeFrance** [comment]
Hello ! Yes I saw this and I agree, this API looks very important.
But to keep an acceptable level of quality for this crate, I think we should have at least one unit test per option.
So when unit test is missing, it takes me some time to do it.

**Comment by vvv** [comment]
Thanks, @CrabeDeFrance!

> But to keep an acceptable level of quality for this crate, I think we should have at least one unit test per option.

Yes, this is sensible. I'll try to do better next time.

**Comment by CrabeDeFrance** [comment]
It's ok, many thanks for the patch ! I was just explaining why there may be some delay.

**Pull request merged**
